export const ICON_IDS = [
  'icon-all_20',
  'icon-emotes_20',
  'icon-skins_20',
  'icon-weapons_20',
  'icon-cookie_20',
  'icon-chevron-down_24',
  'icon-download_24',
  'icon-eye-closed_24',
  'icon-eye-open_24',
  'icon-my-wallet_24',
  'icon-sign-out_24',
  'icon-user_24',
  'icon-arrow-right_24',
  'icon-close_24',
  'icon-gear_24',
  'icon-menu_24',
  'icon-twitch_24',
  'icon-facebook_24',
  'icon-instagram_24',
  'icon-twitter_24',
  'icon-youtube_24',
  'icon-discord_24',
  'icon-circle-triangle_36',
  'icon-team_36',
  'icon-play_36',
  'icon-camera_48',
  'icon-error_48',
  'icon-mark_48',
  'icon-smile_48',
] as const;

export const ICON_SIZES = {
  '20': 'sm',
  '24': 'md',
  '36': 'lg',
  '48': 'xl',
} as const;
